name: hello world workflow

on:
  push:
    branches:
      - main
  pullrequest:
    branches:
      - master
  workflow_dispatch:

job:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: hello world
        run: echo "hello faiz"
        shell: bash  

  goodby:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: hello world
        run: echo "goodby faiz"
        shell: bash     
