name: hello world workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "hello faiz"
        shell: bash

  goodby:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: hello world
        run: echo "goodby faiz"
        shell: bash
